import type { AssetKind, ExportAsset } from '../model/assets';
import type { ExportFile } from '../model/exportFile';
import { getAssetKindDirectory, relativeLink } from './paths';
import { warning, type Diagnostic } from '../model/diagnostics';
export const INLINE_ASSET_LINK_LIMIT = 5;
const mimeMap: [RegExp, AssetKind][] = [[/^image\//,'images'],[/pdf/,'pdfs'],[/presentation|powerpoint/,'presentations'],[/word|text\/plain|document/,'documents'],[/spreadsheet|excel/,'spreadsheets'],[/zip|archive|gzip/,'archives'],[/^audio\//,'audio'],[/^video\//,'video']];
const extMap: Record<string, AssetKind> = { png:'images',jpg:'images',jpeg:'images',gif:'images',svg:'images',webp:'images',pdf:'pdfs',ppt:'presentations',pptx:'presentations',doc:'documents',docx:'documents',txt:'documents',xls:'spreadsheets',xlsx:'spreadsheets',zip:'archives',mp3:'audio',wav:'audio',mp4:'video',mov:'video' };
export function classifyAsset(mime = '', ext = ''): AssetKind { return mimeMap.find(([re])=>re.test(mime.toLowerCase()))?.[1] ?? extMap[ext.replace('.','').toLowerCase()] ?? 'other'; }
export function renderAssetBlocks(blocks: ({type:'text'; markdown:string}|{type:'external'; title:string; url:string}|{type:'asset'; asset:ExportAsset})[], fromFile: string): { markdown: string; files: ExportFile[]; diagnostics: Diagnostic[] } {
 const files: ExportFile[]=[]; const diagnostics: Diagnostic[]=[]; const out:string[]=[]; const counters = new Map<string, number>();
 for (let i=0;i<blocks.length;) { const b=blocks[i]; if (b.type==='text') { out.push(b.markdown); i++; continue; } if (b.type==='external') { out.push(`[${b.title}](${b.url})`); i++; continue; }
  const run = [b.asset]; let j=i+1; while (j<blocks.length && blocks[j].type==='asset' && (blocks[j] as any).asset.kind===b.asset.kind) run.push((blocks[j++] as any).asset);
  if (run.length > INLINE_ASSET_LINK_LIMIT) { const key=`${b.asset.sourceFramePath}:${b.asset.kind}`; const n=(counters.get(key)??0)+1; counters.set(key,n); const dir=`${getAssetKindDirectory(b.asset.sourceFramePath,b.asset.kind)}set-${String(n).padStart(2,'0')}/`; run.forEach(a=>{ a.outputPath=dir+a.name; if (a.bytes) files.push({path:a.outputPath, content:a.bytes, size:a.size??a.bytes.byteLength, type:'asset'}); }); const readme=dir+'README.md'; const manifest=dir+'manifest.json'; files.push({path:readme, content:`# Asset collection\n\nThis folder contains ${run.length} ${b.asset.kind} exported from the Miro frame:\n\n\`${b.asset.sourceFramePath}\`\n\nSee \`manifest.json\` for machine-readable file details.\n`, size:0, type:'readme'}); files.push({path:manifest, content:JSON.stringify({source_frame:b.asset.sourceFramePath,asset_kind:b.asset.kind,count:run.length,files:run.map(a=>({name:a.name,mime_type:a.mimeType,size:a.size,title:a.title,alt:a.alt}))},null,2), size:0, type:'manifest'}); out.push(`**Assets:** [${run.length} ${b.asset.kind}](${relativeLink(fromFile, readme)})`); diagnostics.push(warning('ASSET_BATCH_CREATED', `${run.length} ${b.asset.kind} bundled into ${dir}`)); } else { for (const a of run) { if (a.bytes) files.push({path:a.outputPath,content:a.bytes,size:a.size??a.bytes.byteLength,type:'asset'}); const link=relativeLink(fromFile,a.outputPath); out.push(a.kind==='images' ? `![${a.alt || a.title || a.name}](${link})` : `[${a.title || a.name}](${link})`); } } i=j; }
 return { markdown: out.filter(Boolean).join('\n\n'), files, diagnostics };
}
